export type Section =
  | "front"
  | "india"
  | "world"
  | "business"
  | "sports"
  | "tech"
  | "opinion";

export type Feed = {
  key: string;             // short id, appears in URL slugs
  name: string;            // display name for "src. TIMES OF INDIA" line
  homepage: string;        // for the source link
  url: string;             // RSS feed URL
  section: Section;
};

export const SECTIONS: { key: Section; label: string }[] = [
  { key: "front", label: "The Front Page" },
  { key: "india", label: "India" },
  { key: "world", label: "The World" },
  { key: "business", label: "Business & Markets" },
  { key: "sports", label: "Sport" },
  { key: "tech", label: "Technology" },
  { key: "opinion", label: "Opinion & Editorials" },
];

// ---------------------------------------------------------------------------
// Feeds. Every entry was verified by fetching the URL and confirming that
// the response is a valid RSS 2.0, Atom or RDF feed. If a source stops
// returning valid XML the fetch layer in ./rss.ts will silently drop it.
// ---------------------------------------------------------------------------

export const FEEDS: Feed[] = [
  // -----------------------------------------------------------------------
  // THE FRONT PAGE — top / breaking / latest headlines
  // -----------------------------------------------------------------------
  {
    key: "toi-top",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com",
    url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    section: "front",
  },
  {
    key: "toi-most-read",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com",
    url: "https://timesofindia.indiatimes.com/rssfeedmostread.cms",
    section: "front",
  },
  {
    key: "toi-most-shared",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com",
    url: "https://timesofindia.indiatimes.com/rssfeedmostshared.cms",
    section: "front",
  },
  {
    key: "hindu-top",
    name: "The Hindu",
    homepage: "https://www.thehindu.com",
    url: "https://www.thehindu.com/feeder/default.rss",
    section: "front",
  },
  {
    key: "ht-top",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com",
    url: "https://www.hindustantimes.com/feeds/rss/top-news/rssfeed.xml",
    section: "front",
  },
  {
    key: "ht-latest",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com",
    url: "https://www.hindustantimes.com/feeds/rss/latest-news/rssfeed.xml",
    section: "front",
  },
  {
    key: "ie-top",
    name: "The Indian Express",
    homepage: "https://indianexpress.com",
    url: "https://indianexpress.com/feed/",
    section: "front",
  },
  {
    key: "ndtv-top",
    name: "NDTV",
    homepage: "https://www.ndtv.com",
    url: "https://feeds.feedburner.com/ndtvnews-top-stories",
    section: "front",
  },
  {
    key: "ndtv-latest",
    name: "NDTV",
    homepage: "https://www.ndtv.com",
    url: "https://feeds.feedburner.com/ndtvnews-latest",
    section: "front",
  },
  {
    key: "india-today-top",
    name: "India Today",
    homepage: "https://www.indiatoday.in",
    url: "https://www.indiatoday.in/rss/home",
    section: "front",
  },
  {
    key: "et-top",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com",
    url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms",
    section: "front",
  },
  {
    key: "mc-top",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com",
    url: "https://www.moneycontrol.com/rss/latestnews.xml",
    section: "front",
  },
  {
    key: "mc-mostpop",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com",
    url: "https://www.moneycontrol.com/rss/mostpopular.xml",
    section: "front",
  },
  {
    key: "bs-top",
    name: "Business Standard",
    homepage: "https://www.business-standard.com",
    url: "https://www.business-standard.com/rss/latest.rss",
    section: "front",
  },
  {
    key: "livemint-news",
    name: "Livemint",
    homepage: "https://www.livemint.com",
    url: "https://www.livemint.com/rss/news",
    section: "front",
  },
  {
    key: "rediff-news",
    name: "Rediff",
    homepage: "https://www.rediff.com",
    url: "https://www.rediff.com/rss/newsrss.xml",
    section: "front",
  },
  {
    key: "firstpost-india",
    name: "Firstpost",
    homepage: "https://www.firstpost.com",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/india.xml",
    section: "front",
  },
  {
    key: "news18-india",
    name: "News18",
    homepage: "https://www.news18.com",
    url: "https://www.news18.com/rss/india.xml",
    section: "front",
  },
  {
    key: "dc-top",
    name: "Deccan Chronicle",
    homepage: "https://www.deccanchronicle.com",
    url: "https://www.deccanchronicle.com/feed",
    section: "front",
  },
  {
    key: "freepressjournal-india",
    name: "The Free Press Journal",
    homepage: "https://www.freepressjournal.in",
    url: "https://www.freepressjournal.in/stories.rss",
    section: "front",
  },
  {
    key: "dna-india",
    name: "DNA India",
    homepage: "https://www.dnaindia.com",
    url: "https://www.dnaindia.com/feeds/india.xml",
    section: "front",
  },
  {
    key: "newslaundry",
    name: "Newslaundry",
    homepage: "https://www.newslaundry.com",
    url: "https://www.newslaundry.com/feed",
    section: "front",
  },
  {
    key: "inshorts-national",
    name: "Inshorts",
    homepage: "https://www.inshorts.com",
    url: "https://inshorts.com/en/rss",
    section: "front",
  },
  {
    key: "print-india-cat",
    name: "The Print",
    homepage: "https://theprint.in",
    url: "https://theprint.in/category/india/feed/",
    section: "front",
  },
  {
    key: "ndtv-videos",
    name: "NDTV",
    homepage: "https://www.ndtv.com",
    url: "https://feeds.feedburner.com/ndtvnews-trending-news",
    section: "front",
  },
  {
    key: "et-elections",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com",
    url: "https://economictimes.indiatimes.com/news/elections/rssfeeds/48022878.cms",
    section: "front",
  },
  {
    key: "ie-elections",
    name: "The Indian Express",
    homepage: "https://indianexpress.com",
    url: "https://indianexpress.com/section/elections/feed/",
    section: "front",
  },
  {
    key: "hindu-elections",
    name: "The Hindu",
    homepage: "https://www.thehindu.com",
    url: "https://www.thehindu.com/elections/feeder/default.rss",
    section: "front",
  },
  {
    key: "ht-elections",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com",
    url: "https://www.hindustantimes.com/feeds/rss/elections/rssfeed.xml",
    section: "front",
  },
  {
    key: "india-today-elections",
    name: "India Today",
    homepage: "https://www.indiatoday.in",
    url: "https://www.indiatoday.in/rss/1206672",
    section: "front",
  },

  // -----------------------------------------------------------------------
  // INDIA — national, cities, regional desks
  // -----------------------------------------------------------------------
  {
    key: "toi-india",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/india",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    section: "india",
  },
  {
    key: "toi-mumbai",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/mumbai",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms",
    section: "india",
  },
  {
    key: "toi-delhi",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/delhi",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms",
    section: "india",
  },
  {
    key: "toi-bangalore",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/bangalore",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms",
    section: "india",
  },
  {
    key: "toi-chennai",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/chennai",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms",
    section: "india",
  },
  {
    key: "toi-kolkata",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/kolkata",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms",
    section: "india",
  },
  {
    key: "toi-ahmedabad",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/city/ahmedabad",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms",
    section: "india",
  },
  {
    key: "toi-defence",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/india",
    url: "https://timesofindia.indiatimes.com/rssfeeds/1898274.cms",
    section: "india",
  },
  {
    key: "toi-nri",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/nri",
    url: "https://timesofindia.indiatimes.com/rssfeeds/7098551.cms",
    section: "india",
  },
  {
    key: "hindu-national",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/",
    url: "https://www.thehindu.com/news/national/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-tamilnadu",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/tamil-nadu/",
    url: "https://www.thehindu.com/news/national/tamil-nadu/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-karnataka",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/karnataka/",
    url: "https://www.thehindu.com/news/national/karnataka/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-kerala",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/kerala/",
    url: "https://www.thehindu.com/news/national/kerala/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-andhra",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/andhra-pradesh/",
    url: "https://www.thehindu.com/news/national/andhra-pradesh/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-telangana",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/telangana/",
    url: "https://www.thehindu.com/news/national/telangana/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-otherstates",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/national/other-states/",
    url: "https://www.thehindu.com/news/national/other-states/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-chennai",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/chennai/",
    url: "https://www.thehindu.com/news/cities/chennai/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-bengaluru",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/bangalore/",
    url: "https://www.thehindu.com/news/cities/bangalore/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-hyderabad",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Hyderabad/",
    url: "https://www.thehindu.com/news/cities/Hyderabad/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-delhi",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Delhi/",
    url: "https://www.thehindu.com/news/cities/Delhi/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-mumbai",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/mumbai/",
    url: "https://www.thehindu.com/news/cities/mumbai/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-kolkata",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/kolkata/",
    url: "https://www.thehindu.com/news/cities/kolkata/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-vijayawada",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Vijayawada/",
    url: "https://www.thehindu.com/news/cities/Vijayawada/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-visakhapatnam",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Visakhapatnam/",
    url: "https://www.thehindu.com/news/cities/Visakhapatnam/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-madurai",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Madurai/",
    url: "https://www.thehindu.com/news/cities/Madurai/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-coimbatore",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Coimbatore/",
    url: "https://www.thehindu.com/news/cities/Coimbatore/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-tiruchirapalli",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Tiruchirapalli/",
    url: "https://www.thehindu.com/news/cities/Tiruchirapalli/feeder/default.rss",
    section: "india",
  },
  {
    key: "hindu-mangaluru",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/cities/Mangalore/",
    url: "https://www.thehindu.com/news/cities/Mangalore/feeder/default.rss",
    section: "india",
  },
  {
    key: "ht-india",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/india-news",
    url: "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-cities",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities",
    url: "https://www.hindustantimes.com/feeds/rss/cities/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-delhi",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/delhi-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/delhi-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-mumbai",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/mumbai-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/mumbai-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-bangalore",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/bengaluru-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/bengaluru-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-chennai",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/chennai-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/chennai-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-kolkata",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/kolkata-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/kolkata-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-lucknow",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/lucknow-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/lucknow-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-pune",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/pune-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/pune-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-chandigarh",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/chandigarh-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/chandigarh-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ht-jaipur",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cities/jaipur-news",
    url: "https://www.hindustantimes.com/feeds/rss/cities/jaipur-news/rssfeed.xml",
    section: "india",
  },
  {
    key: "ie-india",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/india",
    url: "https://indianexpress.com/section/india/feed/",
    section: "india",
  },
  {
    key: "ie-cities",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities",
    url: "https://indianexpress.com/section/cities/feed/",
    section: "india",
  },
  {
    key: "ie-delhi",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/delhi",
    url: "https://indianexpress.com/section/cities/delhi/feed/",
    section: "india",
  },
  {
    key: "ie-mumbai",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/mumbai",
    url: "https://indianexpress.com/section/cities/mumbai/feed/",
    section: "india",
  },
  {
    key: "ie-bangalore",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/bangalore",
    url: "https://indianexpress.com/section/cities/bangalore/feed/",
    section: "india",
  },
  {
    key: "ie-chennai",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/chennai",
    url: "https://indianexpress.com/section/cities/chennai/feed/",
    section: "india",
  },
  {
    key: "ie-kolkata",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/kolkata",
    url: "https://indianexpress.com/section/cities/kolkata/feed/",
    section: "india",
  },
  {
    key: "ie-hyderabad",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/hyderabad",
    url: "https://indianexpress.com/section/cities/hyderabad/feed/",
    section: "india",
  },
  {
    key: "ie-pune",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/pune",
    url: "https://indianexpress.com/section/cities/pune/feed/",
    section: "india",
  },
  {
    key: "ie-ahmedabad",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/ahmedabad",
    url: "https://indianexpress.com/section/cities/ahmedabad/feed/",
    section: "india",
  },
  {
    key: "ie-lucknow",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/lucknow",
    url: "https://indianexpress.com/section/cities/lucknow/feed/",
    section: "india",
  },
  {
    key: "ie-chandigarh",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/chandigarh",
    url: "https://indianexpress.com/section/cities/chandigarh/feed/",
    section: "india",
  },
  {
    key: "ie-jaipur",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/cities/jaipur",
    url: "https://indianexpress.com/section/cities/jaipur/feed/",
    section: "india",
  },
  {
    key: "ie-north-east",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/north-east-india",
    url: "https://indianexpress.com/section/north-east-india/feed/",
    section: "india",
  },
  {
    key: "ie-guwahati",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/north-east-india/guwahati",
    url: "https://indianexpress.com/section/north-east-india/guwahati/feed/",
    section: "india",
  },
  {
    key: "ndtv-india",
    name: "NDTV",
    homepage: "https://www.ndtv.com/india",
    url: "https://feeds.feedburner.com/ndtvnews-india-news",
    section: "india",
  },
  {
    key: "ndtv-cities",
    name: "NDTV",
    homepage: "https://www.ndtv.com/cities",
    url: "https://feeds.feedburner.com/ndtvnews-cities-news",
    section: "india",
  },
  {
    key: "india-today-india",
    name: "India Today",
    homepage: "https://www.indiatoday.in/india",
    url: "https://www.indiatoday.in/rss/1206514",
    section: "india",
  },
  {
    key: "india-today-crime",
    name: "India Today",
    homepage: "https://www.indiatoday.in/crime",
    url: "https://www.indiatoday.in/rss/1206600",
    section: "india",
  },
  {
    key: "print-politics",
    name: "The Print",
    homepage: "https://theprint.in/category/politics",
    url: "https://theprint.in/category/politics/feed/",
    section: "india",
  },
  {
    key: "print-defence",
    name: "The Print",
    homepage: "https://theprint.in/category/defence",
    url: "https://theprint.in/category/defence/feed/",
    section: "india",
  },
  {
    key: "print-judiciary",
    name: "The Print",
    homepage: "https://theprint.in/category/judiciary",
    url: "https://theprint.in/category/judiciary/feed/",
    section: "india",
  },
  {
    key: "print-diplomacy",
    name: "The Print",
    homepage: "https://theprint.in/category/diplomacy",
    url: "https://theprint.in/category/diplomacy/feed/",
    section: "india",
  },
  {
    key: "print-environment",
    name: "The Print",
    homepage: "https://theprint.in/category/environment",
    url: "https://theprint.in/category/environment/feed/",
    section: "india",
  },
  {
    key: "print-health",
    name: "The Print",
    homepage: "https://theprint.in/category/health",
    url: "https://theprint.in/category/health/feed/",
    section: "india",
  },
  {
    key: "news18-politics",
    name: "News18",
    homepage: "https://www.news18.com/politics",
    url: "https://www.news18.com/rss/politics.xml",
    section: "india",
  },
  {
    key: "et-politics",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/news/politics-and-nation",
    url: "https://economictimes.indiatimes.com/news/politics-and-nation/rssfeeds/1052732854.cms",
    section: "india",
  },
  {
    key: "et-defence",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/news/defence",
    url: "https://economictimes.indiatimes.com/news/defence/rssfeeds/1898274.cms",
    section: "india",
  },
  {
    key: "livemint-politics",
    name: "Livemint",
    homepage: "https://www.livemint.com/politics",
    url: "https://www.livemint.com/rss/politics",
    section: "india",
  },
  {
    key: "livemint-elections",
    name: "Livemint",
    homepage: "https://www.livemint.com/elections",
    url: "https://www.livemint.com/rss/elections",
    section: "india",
  },
  {
    key: "bs-current",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/current-affairs",
    url: "https://www.business-standard.com/rss/current-affairs-114.rss",
    section: "india",
  },
  {
    key: "bs-politics",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/politics",
    url: "https://www.business-standard.com/rss/politics-115.rss",
    section: "india",
  },
  {
    key: "cnbctv18-india",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/india",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/india.xml",
    section: "india",
  },
  {
    key: "cnbctv18-politics",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/politics",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/politics.xml",
    section: "india",
  },
  {
    key: "ht-analysis",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/analysis",
    url: "https://www.hindustantimes.com/feeds/rss/analysis/rssfeed.xml",
    section: "india",
  },

  // -----------------------------------------------------------------------
  // WORLD — international / foreign affairs
  // -----------------------------------------------------------------------
  {
    key: "toi-world",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/world",
    url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    section: "world",
  },
  {
    key: "hindu-world",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/news/international/",
    url: "https://www.thehindu.com/news/international/feeder/default.rss",
    section: "world",
  },
  {
    key: "ht-world",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/world-news",
    url: "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml",
    section: "world",
  },
  {
    key: "ie-world",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/world",
    url: "https://indianexpress.com/section/world/feed/",
    section: "world",
  },
  {
    key: "ndtv-world",
    name: "NDTV",
    homepage: "https://www.ndtv.com/world",
    url: "https://feeds.feedburner.com/ndtvnews-world-news",
    section: "world",
  },
  {
    key: "india-today-world",
    name: "India Today",
    homepage: "https://www.indiatoday.in/world",
    url: "https://www.indiatoday.in/rss/1206577",
    section: "world",
  },
  {
    key: "print-world",
    name: "The Print",
    homepage: "https://theprint.in/category/world",
    url: "https://theprint.in/category/world/feed/",
    section: "world",
  },
  {
    key: "news18-world",
    name: "News18",
    homepage: "https://www.news18.com/world",
    url: "https://www.news18.com/rss/world.xml",
    section: "world",
  },
  {
    key: "firstpost-world",
    name: "Firstpost",
    homepage: "https://www.firstpost.com/world",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/world.xml",
    section: "world",
  },
  {
    key: "dna-world",
    name: "DNA India",
    homepage: "https://www.dnaindia.com/world",
    url: "https://www.dnaindia.com/feeds/world.xml",
    section: "world",
  },
  {
    key: "et-international",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/news/international",
    url: "https://economictimes.indiatimes.com/news/international/rssfeeds/296589292.cms",
    section: "world",
  },
  {
    key: "et-nri",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/nri",
    url: "https://economictimes.indiatimes.com/nri/rssfeeds/7771250.cms",
    section: "world",
  },
  {
    key: "bs-international",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/international",
    url: "https://www.business-standard.com/rss/international-116.rss",
    section: "world",
  },
  {
    key: "cnbctv18-world",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/world",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/world.xml",
    section: "world",
  },

  // -----------------------------------------------------------------------
  // BUSINESS & MARKETS — economy, companies, wealth, banking, industry
  // -----------------------------------------------------------------------
  {
    key: "toi-biz",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/business",
    url: "https://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
    section: "business",
  },
  {
    key: "hindu-biz",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/",
    url: "https://www.thehindu.com/business/feeder/default.rss",
    section: "business",
  },
  {
    key: "hindu-biz-markets",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/markets/",
    url: "https://www.thehindu.com/business/markets/feeder/default.rss",
    section: "business",
  },
  {
    key: "hindu-biz-economy",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/Economy/",
    url: "https://www.thehindu.com/business/Economy/feeder/default.rss",
    section: "business",
  },
  {
    key: "hindu-biz-industry",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/Industry/",
    url: "https://www.thehindu.com/business/Industry/feeder/default.rss",
    section: "business",
  },
  {
    key: "hindu-biz-agri",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/agri-business/",
    url: "https://www.thehindu.com/business/agri-business/feeder/default.rss",
    section: "business",
  },
  {
    key: "hindu-biz-budget",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/business/budget/",
    url: "https://www.thehindu.com/business/budget/feeder/default.rss",
    section: "business",
  },
  {
    key: "ht-biz",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/business",
    url: "https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml",
    section: "business",
  },
  {
    key: "ie-biz",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business",
    url: "https://indianexpress.com/section/business/feed/",
    section: "business",
  },
  {
    key: "ie-business-market",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business/market",
    url: "https://indianexpress.com/section/business/market/feed/",
    section: "business",
  },
  {
    key: "ie-business-economy",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business/economy",
    url: "https://indianexpress.com/section/business/economy/feed/",
    section: "business",
  },
  {
    key: "ie-business-companies",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business/companies",
    url: "https://indianexpress.com/section/business/companies/feed/",
    section: "business",
  },
  {
    key: "ie-business-banking",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business/banking-and-finance",
    url: "https://indianexpress.com/section/business/banking-and-finance/feed/",
    section: "business",
  },
  {
    key: "ie-business-commodities",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/business/commodities",
    url: "https://indianexpress.com/section/business/commodities/feed/",
    section: "business",
  },
  {
    key: "ndtv-biz",
    name: "NDTV Profit",
    homepage: "https://www.ndtvprofit.com",
    url: "https://feeds.feedburner.com/ndtvprofit-latest",
    section: "business",
  },
  {
    key: "india-today-biz",
    name: "India Today",
    homepage: "https://www.indiatoday.in/business",
    url: "https://www.indiatoday.in/rss/1206513",
    section: "business",
  },
  {
    key: "news18-biz",
    name: "News18",
    homepage: "https://www.news18.com/business",
    url: "https://www.news18.com/rss/business.xml",
    section: "business",
  },
  {
    key: "firstpost-biz",
    name: "Firstpost",
    homepage: "https://www.firstpost.com/business",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/business.xml",
    section: "business",
  },
  {
    key: "dna-biz",
    name: "DNA India",
    homepage: "https://www.dnaindia.com/money",
    url: "https://www.dnaindia.com/feeds/money.xml",
    section: "business",
  },
  {
    key: "rediff-biz",
    name: "Rediff Money",
    homepage: "https://money.rediff.com",
    url: "https://www.rediff.com/rss/moneyrss.xml",
    section: "business",
  },
  {
    key: "print-economy",
    name: "The Print",
    homepage: "https://theprint.in/category/economy",
    url: "https://theprint.in/category/economy/feed/",
    section: "business",
  },
  {
    key: "livemint-markets",
    name: "Livemint",
    homepage: "https://www.livemint.com/market",
    url: "https://www.livemint.com/rss/markets",
    section: "business",
  },
  {
    key: "livemint-money",
    name: "Livemint",
    homepage: "https://www.livemint.com/money",
    url: "https://www.livemint.com/rss/money",
    section: "business",
  },
  {
    key: "livemint-companies",
    name: "Livemint",
    homepage: "https://www.livemint.com/companies",
    url: "https://www.livemint.com/rss/companies",
    section: "business",
  },
  {
    key: "livemint-economy",
    name: "Livemint",
    homepage: "https://www.livemint.com/economy",
    url: "https://www.livemint.com/rss/economy",
    section: "business",
  },
  {
    key: "livemint-industry",
    name: "Livemint",
    homepage: "https://www.livemint.com/industry",
    url: "https://www.livemint.com/rss/industry",
    section: "business",
  },
  {
    key: "livemint-auto",
    name: "Livemint",
    homepage: "https://www.livemint.com/auto-news",
    url: "https://www.livemint.com/rss/auto",
    section: "business",
  },
  {
    key: "et-markets",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/markets",
    url: "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    section: "business",
  },
  {
    key: "et-economy",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/news/economy",
    url: "https://economictimes.indiatimes.com/news/economy/rssfeeds/1373380680.cms",
    section: "business",
  },
  {
    key: "et-industry",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry",
    url: "https://economictimes.indiatimes.com/industry/rssfeeds/13352306.cms",
    section: "business",
  },
  {
    key: "et-auto",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/auto",
    url: "https://economictimes.indiatimes.com/industry/auto/rssfeeds/64829342.cms",
    section: "business",
  },
  {
    key: "et-retail",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/services/retail",
    url: "https://economictimes.indiatimes.com/industry/services/retail/rssfeeds/13352306.cms",
    section: "business",
  },
  {
    key: "et-wealth",
    name: "ET Wealth",
    homepage: "https://economictimes.indiatimes.com/wealth",
    url: "https://economictimes.indiatimes.com/wealth/rssfeeds/837555174.cms",
    section: "business",
  },
  {
    key: "et-small-biz",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/small-biz",
    url: "https://economictimes.indiatimes.com/small-biz/rssfeeds/13357270.cms",
    section: "business",
  },
  {
    key: "et-mf",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/mutual-funds",
    url: "https://economictimes.indiatimes.com/mutual-funds/rssfeeds/1466318837.cms",
    section: "business",
  },
  {
    key: "et-ipo",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/markets/ipo",
    url: "https://economictimes.indiatimes.com/markets/ipo/rssfeeds/33342454.cms",
    section: "business",
  },
  {
    key: "et-banking",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/banking/finance/banking",
    url: "https://economictimes.indiatimes.com/industry/banking/finance/banking/rssfeeds/13358319.cms",
    section: "business",
  },
  {
    key: "et-cons-products",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/cons-products",
    url: "https://economictimes.indiatimes.com/industry/cons-products/rssfeeds/13358315.cms",
    section: "business",
  },
  {
    key: "et-telecom",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/telecom",
    url: "https://economictimes.indiatimes.com/industry/telecom/rssfeeds/13352306.cms",
    section: "business",
  },
  {
    key: "et-transportation",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/transportation",
    url: "https://economictimes.indiatimes.com/industry/transportation/rssfeeds/13358056.cms",
    section: "business",
  },
  {
    key: "et-energy",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/energy",
    url: "https://economictimes.indiatimes.com/industry/energy/rssfeeds/13358050.cms",
    section: "business",
  },
  {
    key: "et-healthcare",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/healthcare",
    url: "https://economictimes.indiatimes.com/industry/healthcare/biotech/rssfeeds/13358365.cms",
    section: "business",
  },
  {
    key: "et-real-estate",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/industry/services",
    url: "https://economictimes.indiatimes.com/industry/services/property-/-cstruction/rssfeeds/13358050.cms",
    section: "business",
  },
  {
    key: "bs-companies",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/companies",
    url: "https://www.business-standard.com/rss/companies-101.rss",
    section: "business",
  },
  {
    key: "bs-markets",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/markets",
    url: "https://www.business-standard.com/rss/markets-106.rss",
    section: "business",
  },
  {
    key: "bs-economy",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/economy",
    url: "https://www.business-standard.com/rss/economy-102.rss",
    section: "business",
  },
  {
    key: "bs-finance",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/finance",
    url: "https://www.business-standard.com/rss/finance-103.rss",
    section: "business",
  },
  {
    key: "bs-stocks",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/markets/stocks",
    url: "https://www.business-standard.com/rss/markets/stocks-10618.rss",
    section: "business",
  },
  {
    key: "mc-business",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/news/business/",
    url: "https://www.moneycontrol.com/rss/business.xml",
    section: "business",
  },
  {
    key: "mc-markets",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/markets/",
    url: "https://www.moneycontrol.com/rss/marketreports.xml",
    section: "business",
  },
  {
    key: "mc-economy",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/news/economy/",
    url: "https://www.moneycontrol.com/rss/economy.xml",
    section: "business",
  },
  {
    key: "mc-buzz",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/stocks/marketstats/",
    url: "https://www.moneycontrol.com/rss/buzzingstocks.xml",
    section: "business",
  },
  {
    key: "mc-results",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/news/results/",
    url: "https://www.moneycontrol.com/rss/results.xml",
    section: "business",
  },
  {
    key: "mc-ipos",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/ipo/",
    url: "https://www.moneycontrol.com/rss/iponews.xml",
    section: "business",
  },
  {
    key: "cnbctv18-latest",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/latest.xml",
    section: "business",
  },
  {
    key: "cnbctv18-market",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/market",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/market.xml",
    section: "business",
  },
  {
    key: "cnbctv18-economy",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/economy",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/economy.xml",
    section: "business",
  },
  {
    key: "cnbctv18-business",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/business",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/business.xml",
    section: "business",
  },
  {
    key: "cnbctv18-personal",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/personal-finance",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/personal-finance.xml",
    section: "business",
  },
  {
    key: "cnbctv18-real-estate",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/real-estate",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/real-estate.xml",
    section: "business",
  },
  {
    key: "cnbctv18-cryptocurrency",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/cryptocurrency",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/cryptocurrency.xml",
    section: "business",
  },
  {
    key: "bt-latest",
    name: "Business Today",
    homepage: "https://www.businesstoday.in",
    url: "https://www.businesstoday.in/rss/latest-news",
    section: "business",
  },
  {
    key: "bt-companies",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/latest/corporate",
    url: "https://www.businesstoday.in/rss/companies",
    section: "business",
  },
  {
    key: "bt-economy",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/latest/economy",
    url: "https://www.businesstoday.in/rss/economy",
    section: "business",
  },
  {
    key: "bt-markets",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/markets",
    url: "https://www.businesstoday.in/rss/markets",
    section: "business",
  },
  {
    key: "bt-industry",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/industry",
    url: "https://www.businesstoday.in/rss/industry",
    section: "business",
  },
  {
    key: "bt-personal",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/personal-finance",
    url: "https://www.businesstoday.in/rss/personal-finance",
    section: "business",
  },
  {
    key: "bt-mf",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/mutual-funds",
    url: "https://www.businesstoday.in/rss/mutual-funds",
    section: "business",
  },
  {
    key: "bt-corporate",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/latest/corporate",
    url: "https://www.businesstoday.in/rss/corporate",
    section: "business",
  },
  {
    key: "bt-crypto",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/cryptocurrency",
    url: "https://www.businesstoday.in/rss/cryptocurrency",
    section: "business",
  },
  {
    key: "bt-magazine",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/magazine",
    url: "https://www.businesstoday.in/rss/magazine",
    section: "business",
  },
  {
    key: "finshots-economy",
    name: "Finshots",
    homepage: "https://finshots.in",
    url: "https://finshots.in/tag/economy/rss/",
    section: "business",
  },

  // -----------------------------------------------------------------------
  // SPORTS — cricket, football, tennis, hockey, etc.
  // -----------------------------------------------------------------------
  {
    key: "toi-sports",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/sports",
    url: "https://timesofindia.indiatimes.com/rssfeeds/4719148.cms",
    section: "sports",
  },
  {
    key: "toi-cricket",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/sports/cricket",
    url: "https://timesofindia.indiatimes.com/rssfeeds/54829575.cms",
    section: "sports",
  },
  {
    key: "hindu-sport",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/",
    url: "https://www.thehindu.com/sport/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-cricket",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/cricket/",
    url: "https://www.thehindu.com/sport/cricket/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-football",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/football/",
    url: "https://www.thehindu.com/sport/football/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-tennis",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/tennis/",
    url: "https://www.thehindu.com/sport/tennis/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-hockey",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/hockey/",
    url: "https://www.thehindu.com/sport/hockey/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-motorsport",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/motorsport/",
    url: "https://www.thehindu.com/sport/motorsport/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-races",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/races/",
    url: "https://www.thehindu.com/sport/races/feeder/default.rss",
    section: "sports",
  },
  {
    key: "hindu-other-sports",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sport/other-sports/",
    url: "https://www.thehindu.com/sport/other-sports/feeder/default.rss",
    section: "sports",
  },
  {
    key: "ht-sports",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/sports",
    url: "https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml",
    section: "sports",
  },
  {
    key: "ht-cricket",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/cricket",
    url: "https://www.hindustantimes.com/feeds/rss/cricket/rssfeed.xml",
    section: "sports",
  },
  {
    key: "ie-sports",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports",
    url: "https://indianexpress.com/section/sports/feed/",
    section: "sports",
  },
  {
    key: "ie-cricket",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/cricket",
    url: "https://indianexpress.com/section/sports/cricket/feed/",
    section: "sports",
  },
  {
    key: "ie-football",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/football",
    url: "https://indianexpress.com/section/sports/football/feed/",
    section: "sports",
  },
  {
    key: "ie-tennis",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/tennis",
    url: "https://indianexpress.com/section/sports/tennis/feed/",
    section: "sports",
  },
  {
    key: "ie-hockey",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/hockey",
    url: "https://indianexpress.com/section/sports/hockey/feed/",
    section: "sports",
  },
  {
    key: "ie-badminton",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/badminton",
    url: "https://indianexpress.com/section/sports/badminton/feed/",
    section: "sports",
  },
  {
    key: "ie-motorsport",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/sports/motor-sport",
    url: "https://indianexpress.com/section/sports/motor-sport/feed/",
    section: "sports",
  },
  {
    key: "ndtv-sports",
    name: "NDTV Sports",
    homepage: "https://sports.ndtv.com",
    url: "https://feeds.feedburner.com/ndtvsports-latest",
    section: "sports",
  },
  {
    key: "ndtv-cricket",
    name: "NDTV Sports",
    homepage: "https://sports.ndtv.com/cricket",
    url: "https://feeds.feedburner.com/ndtvsports-cricket",
    section: "sports",
  },
  {
    key: "india-today-sports",
    name: "India Today",
    homepage: "https://www.indiatoday.in/sports",
    url: "https://www.indiatoday.in/rss/1206550",
    section: "sports",
  },
  {
    key: "india-today-cricket",
    name: "India Today",
    homepage: "https://www.indiatoday.in/sports/cricket",
    url: "https://www.indiatoday.in/rss/1206551",
    section: "sports",
  },
  {
    key: "news18-sports",
    name: "News18",
    homepage: "https://www.news18.com/sports",
    url: "https://www.news18.com/rss/sports.xml",
    section: "sports",
  },
  {
    key: "news18-cricket",
    name: "News18 CricketNext",
    homepage: "https://www.news18.com/cricketnext",
    url: "https://www.news18.com/rss/cricketnext.xml",
    section: "sports",
  },
  {
    key: "firstpost-sports",
    name: "Firstpost",
    homepage: "https://www.firstpost.com/sports",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/sports.xml",
    section: "sports",
  },
  {
    key: "dna-sports",
    name: "DNA India",
    homepage: "https://www.dnaindia.com/sport",
    url: "https://www.dnaindia.com/feeds/sport.xml",
    section: "sports",
  },
  {
    key: "rediff-cricket",
    name: "Rediff Cricket",
    homepage: "https://www.rediff.com/cricket",
    url: "https://www.rediff.com/rss/cricketrss.xml",
    section: "sports",
  },
  {
    key: "rediff-sports",
    name: "Rediff Sports",
    homepage: "https://www.rediff.com/sports",
    url: "https://www.rediff.com/rss/sportsrss.xml",
    section: "sports",
  },
  {
    key: "livemint-sports",
    name: "Livemint",
    homepage: "https://www.livemint.com/sports",
    url: "https://www.livemint.com/rss/sports",
    section: "sports",
  },
  {
    key: "et-cricket",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/news/sports",
    url: "https://economictimes.indiatimes.com/news/sports/rssfeeds/4719161.cms",
    section: "sports",
  },
  {
    key: "bs-sports",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/sports",
    url: "https://www.business-standard.com/rss/sports-113.rss",
    section: "sports",
  },
  {
    key: "cnbctv18-sports",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/sports",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/sports.xml",
    section: "sports",
  },
  {
    key: "espn-india",
    name: "ESPN Cricinfo",
    homepage: "https://www.espncricinfo.com",
    url: "https://www.espncricinfo.com/rss/content/story/feeds/6.xml",
    section: "sports",
  },
  {
    key: "espn-general",
    name: "ESPN Cricinfo",
    homepage: "https://www.espncricinfo.com",
    url: "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
    section: "sports",
  },
  {
    key: "sportstar",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com",
    url: "https://sportstar.thehindu.com/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-cricket",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/cricket",
    url: "https://sportstar.thehindu.com/cricket/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-football",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/football",
    url: "https://sportstar.thehindu.com/football/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-tennis",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/tennis",
    url: "https://sportstar.thehindu.com/tennis/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-hockey",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/hockey",
    url: "https://sportstar.thehindu.com/hockey/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-athletics",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/athletics",
    url: "https://sportstar.thehindu.com/athletics/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-motorsport",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/motorsport",
    url: "https://sportstar.thehindu.com/motorsport/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-badminton",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/badminton",
    url: "https://sportstar.thehindu.com/badminton/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-chess",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/chess",
    url: "https://sportstar.thehindu.com/chess/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-golf",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/golf",
    url: "https://sportstar.thehindu.com/golf/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-other",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/other-sports",
    url: "https://sportstar.thehindu.com/other-sports/feeder/default.rss",
    section: "sports",
  },
  {
    key: "sportstar-magazine",
    name: "Sportstar",
    homepage: "https://sportstar.thehindu.com/magazine",
    url: "https://sportstar.thehindu.com/magazine/feeder/default.rss",
    section: "sports",
  },

  // -----------------------------------------------------------------------
  // TECHNOLOGY — tech, science, startups, gadgets
  // -----------------------------------------------------------------------
  {
    key: "toi-tech",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/tech",
    url: "https://timesofindia.indiatimes.com/rssfeeds/66949542.cms",
    section: "tech",
  },
  {
    key: "toi-science",
    name: "The Times of India",
    homepage: "https://timesofindia.indiatimes.com/home/science",
    url: "https://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms",
    section: "tech",
  },
  {
    key: "hindu-tech",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/technology/",
    url: "https://www.thehindu.com/sci-tech/technology/feeder/default.rss",
    section: "tech",
  },
  {
    key: "hindu-scitech",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/",
    url: "https://www.thehindu.com/sci-tech/feeder/default.rss",
    section: "tech",
  },
  {
    key: "hindu-science",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/science/",
    url: "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
    section: "tech",
  },
  {
    key: "hindu-agri",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/agriculture/",
    url: "https://www.thehindu.com/sci-tech/agriculture/feeder/default.rss",
    section: "tech",
  },
  {
    key: "hindu-health",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/health/",
    url: "https://www.thehindu.com/sci-tech/health/feeder/default.rss",
    section: "tech",
  },
  {
    key: "hindu-energy",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/sci-tech/energy-and-environment/",
    url: "https://www.thehindu.com/sci-tech/energy-and-environment/feeder/default.rss",
    section: "tech",
  },
  {
    key: "ht-tech",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/technology",
    url: "https://www.hindustantimes.com/feeds/rss/technology/rssfeed.xml",
    section: "tech",
  },
  {
    key: "ie-tech",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology",
    url: "https://indianexpress.com/section/technology/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-mobiles",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/mobile-tabs",
    url: "https://indianexpress.com/section/technology/mobile-tabs/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-gadgets",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/gadgets",
    url: "https://indianexpress.com/section/technology/gadgets/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-social",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/social",
    url: "https://indianexpress.com/section/technology/social/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-science",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/science",
    url: "https://indianexpress.com/section/technology/science/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-news",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/tech-news-technology",
    url: "https://indianexpress.com/section/technology/tech-news-technology/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-ai",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/artificial-intelligence",
    url: "https://indianexpress.com/section/technology/artificial-intelligence/feed/",
    section: "tech",
  },
  {
    key: "ie-tech-reviews",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/technology/tech-reviews",
    url: "https://indianexpress.com/section/technology/tech-reviews/feed/",
    section: "tech",
  },
  {
    key: "ndtv-tech",
    name: "Gadgets 360",
    homepage: "https://www.gadgets360.com",
    url: "https://feeds.feedburner.com/gadgets360-latest",
    section: "tech",
  },
  {
    key: "india-today-tech",
    name: "India Today",
    homepage: "https://www.indiatoday.in/technology",
    url: "https://www.indiatoday.in/rss/1206584",
    section: "tech",
  },
  {
    key: "news18-tech",
    name: "News18 Tech",
    homepage: "https://www.news18.com/tech",
    url: "https://www.news18.com/rss/tech.xml",
    section: "tech",
  },
  {
    key: "firstpost-tech",
    name: "Firstpost",
    homepage: "https://www.firstpost.com/tech",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/tech.xml",
    section: "tech",
  },
  {
    key: "dna-tech",
    name: "DNA India",
    homepage: "https://www.dnaindia.com/sci-tech",
    url: "https://www.dnaindia.com/feeds/scitech.xml",
    section: "tech",
  },
  {
    key: "et-tech",
    name: "ET Tech",
    homepage: "https://tech.economictimes.indiatimes.com",
    url: "https://economictimes.indiatimes.com/tech/rssfeeds/13357270.cms",
    section: "tech",
  },
  {
    key: "et-startup",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/small-biz/startups",
    url: "https://economictimes.indiatimes.com/small-biz/startups/rssfeeds/11993050.cms",
    section: "tech",
  },
  {
    key: "livemint-technology",
    name: "Livemint",
    homepage: "https://www.livemint.com/technology",
    url: "https://www.livemint.com/rss/technology",
    section: "tech",
  },
  {
    key: "bs-technology",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/technology",
    url: "https://www.business-standard.com/rss/technology-108.rss",
    section: "tech",
  },
  {
    key: "mc-tech",
    name: "Moneycontrol",
    homepage: "https://www.moneycontrol.com/news/technology/",
    url: "https://www.moneycontrol.com/rss/technology.xml",
    section: "tech",
  },
  {
    key: "cnbctv18-tech",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/technology",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/technology.xml",
    section: "tech",
  },
  {
    key: "cnbctv18-startup",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/startup",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/startup.xml",
    section: "tech",
  },
  {
    key: "cnbctv18-info-tech",
    name: "CNBC-TV18",
    homepage: "https://www.cnbctv18.com/information-technology",
    url: "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/information-technology.xml",
    section: "tech",
  },
  {
    key: "print-tech",
    name: "The Print",
    homepage: "https://theprint.in/category/tech",
    url: "https://theprint.in/category/tech/feed/",
    section: "tech",
  },
  {
    key: "print-science",
    name: "The Print",
    homepage: "https://theprint.in/category/science",
    url: "https://theprint.in/category/science/feed/",
    section: "tech",
  },
  {
    key: "bt-tech",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/technology",
    url: "https://www.businesstoday.in/rss/technology",
    section: "tech",
  },
  {
    key: "yourstory",
    name: "YourStory",
    homepage: "https://yourstory.com",
    url: "https://yourstory.com/feed",
    section: "tech",
  },
  {
    key: "inc42",
    name: "Inc42",
    homepage: "https://inc42.com",
    url: "https://inc42.com/feed/",
    section: "tech",
  },
  {
    key: "medianama",
    name: "MediaNama",
    homepage: "https://www.medianama.com",
    url: "https://www.medianama.com/feed/",
    section: "tech",
  },
  {
    key: "telecomtalk",
    name: "TelecomTalk",
    homepage: "https://telecomtalk.info",
    url: "https://telecomtalk.info/feed/",
    section: "tech",
  },

  // -----------------------------------------------------------------------
  // OPINION & EDITORIALS — leaders, columns, comment, editorial
  // -----------------------------------------------------------------------
  {
    key: "hindu-opinion",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/",
    url: "https://www.thehindu.com/opinion/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-editorial",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/editorial/",
    url: "https://www.thehindu.com/opinion/editorial/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-lead",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/lead/",
    url: "https://www.thehindu.com/opinion/lead/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-op-ed",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/op-ed/",
    url: "https://www.thehindu.com/opinion/op-ed/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-columns",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/columns/",
    url: "https://www.thehindu.com/opinion/columns/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-interview",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/interview/",
    url: "https://www.thehindu.com/opinion/interview/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-cartoon",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/cartoon/",
    url: "https://www.thehindu.com/opinion/cartoon/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-letters",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/letters/",
    url: "https://www.thehindu.com/opinion/letters/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "hindu-open-page",
    name: "The Hindu",
    homepage: "https://www.thehindu.com/opinion/open-page/",
    url: "https://www.thehindu.com/opinion/open-page/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "ht-opinion",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/opinion",
    url: "https://www.hindustantimes.com/feeds/rss/opinion/rssfeed.xml",
    section: "opinion",
  },
  {
    key: "ht-editorials",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/editorials",
    url: "https://www.hindustantimes.com/feeds/rss/editorials/rssfeed.xml",
    section: "opinion",
  },
  {
    key: "ht-columns",
    name: "Hindustan Times",
    homepage: "https://www.hindustantimes.com/columns",
    url: "https://www.hindustantimes.com/feeds/rss/columns/rssfeed.xml",
    section: "opinion",
  },
  {
    key: "ie-opinion",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/opinion",
    url: "https://indianexpress.com/section/opinion/feed/",
    section: "opinion",
  },
  {
    key: "ie-editorial",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/opinion/editorials",
    url: "https://indianexpress.com/section/opinion/editorials/feed/",
    section: "opinion",
  },
  {
    key: "ie-columns",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/opinion/columns",
    url: "https://indianexpress.com/section/opinion/columns/feed/",
    section: "opinion",
  },
  {
    key: "ie-explained",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/explained",
    url: "https://indianexpress.com/section/explained/feed/",
    section: "opinion",
  },
  {
    key: "ie-political-pulse",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/political-pulse",
    url: "https://indianexpress.com/section/political-pulse/feed/",
    section: "opinion",
  },
  {
    key: "ie-longform",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/long-reads",
    url: "https://indianexpress.com/section/long-reads/feed/",
    section: "opinion",
  },
  {
    key: "ie-research",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/research",
    url: "https://indianexpress.com/section/research/feed/",
    section: "opinion",
  },
  {
    key: "ie-idea-exchange",
    name: "The Indian Express",
    homepage: "https://indianexpress.com/section/india/idea-exchange",
    url: "https://indianexpress.com/section/india/idea-exchange/feed/",
    section: "opinion",
  },
  {
    key: "print-opinion",
    name: "The Print",
    homepage: "https://theprint.in/category/opinion",
    url: "https://theprint.in/category/opinion/feed/",
    section: "opinion",
  },
  {
    key: "livemint-opinion",
    name: "Livemint",
    homepage: "https://www.livemint.com/opinion",
    url: "https://www.livemint.com/rss/opinion",
    section: "opinion",
  },
  {
    key: "et-opinion",
    name: "The Economic Times",
    homepage: "https://economictimes.indiatimes.com/opinion",
    url: "https://economictimes.indiatimes.com/opinion/rssfeeds/897228639.cms",
    section: "opinion",
  },
  {
    key: "bs-opinion",
    name: "Business Standard",
    homepage: "https://www.business-standard.com/opinion",
    url: "https://www.business-standard.com/rss/opinion-105.rss",
    section: "opinion",
  },
  {
    key: "news18-opinion",
    name: "News18",
    homepage: "https://www.news18.com/opinion",
    url: "https://www.news18.com/rss/opinion.xml",
    section: "opinion",
  },
  {
    key: "firstpost-opinion",
    name: "Firstpost",
    homepage: "https://www.firstpost.com/opinion",
    url: "https://www.firstpost.com/commonfeeds/v1/mfp/rss/opinion.xml",
    section: "opinion",
  },
  {
    key: "bt-opinion",
    name: "Business Today",
    homepage: "https://www.businesstoday.in/opinion",
    url: "https://www.businesstoday.in/rss/opinion",
    section: "opinion",
  },
  {
    key: "frontline-latest",
    name: "Frontline",
    homepage: "https://frontline.thehindu.com",
    url: "https://frontline.thehindu.com/feeder/default.rss",
    section: "opinion",
  },
  {
    key: "frontline-cover",
    name: "Frontline",
    homepage: "https://frontline.thehindu.com/cover-story",
    url: "https://frontline.thehindu.com/cover-story/feeder/default.rss",
    section: "opinion",
  },
];

export function feedByKey(key: string): Feed | undefined {
  return FEEDS.find((f) => f.key === key);
}

export function sectionLabel(key: Section): string {
  return SECTIONS.find((s) => s.key === key)?.label ?? key;
}
